repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [ python ]
      - id: ruff
        name: ruff
        entry: poetry run ruff . --fix
        language: system
        types: [ python ]